apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: azure-disk
  namespace: kubeflow
spec:
  resources:
    requests:
      storage: 0.5Gi
  storageClassName: standard
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
